# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

container:
  image: salt-spm:linux-amd64
  endpoint: acr-salt
  volumes:
    - /home/vsts/work/1/a:/srv/spm_build

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo /entry-point.sh build .
- publish: $(Build.ArtifactStagingDirectory)
  artifact: spm
